'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AppInterface
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SABBPlugin.AppInterface", GetType(AppInterface).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Approved.
        '''</summary>
        Friend Shared ReadOnly Property Approved() As String
            Get
                Return ResourceManager.GetString("Approved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Sessions.
        '''</summary>
        Friend Shared ReadOnly Property btnShowSessions() As String
            Get
                Return ResourceManager.GetString("btnShowSessions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canceled.
        '''</summary>
        Friend Shared ReadOnly Property Canceled() As String
            Get
                Return ResourceManager.GetString("Canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closed.
        '''</summary>
        Friend Shared ReadOnly Property Closed() As String
            Get
                Return ResourceManager.GetString("Closed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Filteration.
        '''</summary>
        Friend Shared ReadOnly Property CustomerFilteration() As String
            Get
                Return ResourceManager.GetString("CustomerFilteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Return.
        '''</summary>
        Friend Shared ReadOnly Property CustomerReturn() As String
            Get
                Return ResourceManager.GetString("CustomerReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customers.
        '''</summary>
        Friend Shared ReadOnly Property Customers() As String
            Get
                Return ResourceManager.GetString("Customers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direct Receiving.
        '''</summary>
        Friend Shared ReadOnly Property DirectReceiving() As String
            Get
                Return ResourceManager.GetString("DirectReceiving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doc#.
        '''</summary>
        Friend Shared ReadOnly Property DocNum() As String
            Get
                Return ResourceManager.GetString("DocNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO Receiving.
        '''</summary>
        Friend Shared ReadOnly Property DOReceiving() As String
            Get
                Return ResourceManager.GetString("DOReceiving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exchanged.
        '''</summary>
        Friend Shared ReadOnly Property Exchanged() As String
            Get
                Return ResourceManager.GetString("Exchanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field Constraint.
        '''</summary>
        Friend Shared ReadOnly Property FieldConstraint() As String
            Get
                Return ResourceManager.GetString("FieldConstraint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empty not allowed..
        '''</summary>
        Friend Shared ReadOnly Property FieldEmptynotallowed() As String
            Get
                Return ResourceManager.GetString("FieldEmptynotallowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max length ={0}.
        '''</summary>
        Friend Shared ReadOnly Property FieldMaxLength() As String
            Get
                Return ResourceManager.GetString("FieldMaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field value must be unique..
        '''</summary>
        Friend Shared ReadOnly Property FieldUnique() As String
            Get
                Return ResourceManager.GetString("FieldUnique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Customer.
        '''</summary>
        Friend Shared ReadOnly Property FromCustomer() As String
            Get
                Return ResourceManager.GetString("FromCustomer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Warehouse.
        '''</summary>
        Friend Shared ReadOnly Property FromWarehouse() As String
            Get
                Return ResourceManager.GetString("FromWarehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Grand Total=.
        '''</summary>
        Friend Shared ReadOnly Property GrandTotal() As String
            Get
                Return ResourceManager.GetString("GrandTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GTN #.
        '''</summary>
        Friend Shared ReadOnly Property GTNNum() As String
            Get
                Return ResourceManager.GetString("GTNNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Friend Shared ReadOnly Property Inventory() As String
            Get
                Return ResourceManager.GetString("Inventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issuance Date.
        '''</summary>
        Friend Shared ReadOnly Property IssuanceDate() As String
            Get
                Return ResourceManager.GetString("IssuanceDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issued.
        '''</summary>
        Friend Shared ReadOnly Property Issued() As String
            Get
                Return ResourceManager.GetString("Issued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Printing List.
        '''</summary>
        Friend Shared ReadOnly Property ItemPrintingList() As String
            Get
                Return ResourceManager.GetString("ItemPrintingList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Return.
        '''</summary>
        Friend Shared ReadOnly Property ItemReturn() As String
            Get
                Return ResourceManager.GetString("ItemReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Filteration.
        '''</summary>
        Friend Shared ReadOnly Property LocationFilteration() As String
            Get
                Return ResourceManager.GetString("LocationFilteration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locations.
        '''</summary>
        Friend Shared ReadOnly Property Locations() As String
            Get
                Return ResourceManager.GetString("Locations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Movement Date.
        '''</summary>
        Friend Shared ReadOnly Property MovementDate() As String
            Get
                Return ResourceManager.GetString("MovementDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRN #.
        '''</summary>
        Friend Shared ReadOnly Property MRNNum() As String
            Get
                Return ResourceManager.GetString("MRNNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property NewPO() As String
            Get
                Return ResourceManager.GetString("NewPO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property NewWO() As String
            Get
                Return ResourceManager.GetString("NewWO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paid.
        '''</summary>
        Friend Shared ReadOnly Property Paid() As String
            Get
                Return ResourceManager.GetString("Paid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partial Issued.
        '''</summary>
        Friend Shared ReadOnly Property PartialIssued() As String
            Get
                Return ResourceManager.GetString("PartialIssued", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partial.
        '''</summary>
        Friend Shared ReadOnly Property PartialPayment() As String
            Get
                Return ResourceManager.GetString("PartialPayment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partial Received.
        '''</summary>
        Friend Shared ReadOnly Property PartialReceived() As String
            Get
                Return ResourceManager.GetString("PartialReceived", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pending.
        '''</summary>
        Friend Shared ReadOnly Property Pending() As String
            Get
                Return ResourceManager.GetString("Pending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Posted.
        '''</summary>
        Friend Shared ReadOnly Property Posted() As String
            Get
                Return ResourceManager.GetString("Posted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prepared.
        '''</summary>
        Friend Shared ReadOnly Property Prepared() As String
            Get
                Return ResourceManager.GetString("Prepared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received.
        '''</summary>
        Friend Shared ReadOnly Property Received() As String
            Get
                Return ResourceManager.GetString("Received", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property Refresh() As String
            Get
                Return ResourceManager.GetString("Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return Date.
        '''</summary>
        Friend Shared ReadOnly Property ReturnDate() As String
            Get
                Return ResourceManager.GetString("ReturnDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Returned.
        '''</summary>
        Friend Shared ReadOnly Property Returned() As String
            Get
                Return ResourceManager.GetString("Returned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show all categories.
        '''</summary>
        Friend Shared ReadOnly Property ShowAllCategories() As String
            Get
                Return ResourceManager.GetString("ShowAllCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show all customers.
        '''</summary>
        Friend Shared ReadOnly Property ShowAllCustomers() As String
            Get
                Return ResourceManager.GetString("ShowAllCustomers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show All Locations.
        '''</summary>
        Friend Shared ReadOnly Property ShowAllLocations() As String
            Get
                Return ResourceManager.GetString("ShowAllLocations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Report.
        '''</summary>
        Friend Shared ReadOnly Property ShowReport() As String
            Get
                Return ResourceManager.GetString("ShowReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show specific categories.
        '''</summary>
        Friend Shared ReadOnly Property ShowSpecificCategories() As String
            Get
                Return ResourceManager.GetString("ShowSpecificCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show specific customers.
        '''</summary>
        Friend Shared ReadOnly Property ShowSpecificCustomers() As String
            Get
                Return ResourceManager.GetString("ShowSpecificCustomers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Specific Locations.
        '''</summary>
        Friend Shared ReadOnly Property ShowSpecificLocations() As String
            Get
                Return ResourceManager.GetString("ShowSpecificLocations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock:.
        '''</summary>
        Friend Shared ReadOnly Property Stock() As String
            Get
                Return ResourceManager.GetString("Stock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock Issuance.
        '''</summary>
        Friend Shared ReadOnly Property StockIssuance() As String
            Get
                Return ResourceManager.GetString("StockIssuance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock Movement.
        '''</summary>
        Friend Shared ReadOnly Property StockMovement() As String
            Get
                Return ResourceManager.GetString("StockMovement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum Discount=.
        '''</summary>
        Friend Shared ReadOnly Property SumDiscount() As String
            Get
                Return ResourceManager.GetString("SumDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum QTY=.
        '''</summary>
        Friend Shared ReadOnly Property SumQTY() As String
            Get
                Return ResourceManager.GetString("SumQTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend Shared ReadOnly Property Supplier() As String
            Get
                Return ResourceManager.GetString("Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Custodian.
        '''</summary>
        Friend Shared ReadOnly Property ToCustodian() As String
            Get
                Return ResourceManager.GetString("ToCustodian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Supplier.
        '''</summary>
        Friend Shared ReadOnly Property ToSupplier() As String
            Get
                Return ResourceManager.GetString("ToSupplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfered.
        '''</summary>
        Friend Shared ReadOnly Property Transfered() As String
            Get
                Return ResourceManager.GetString("Transfered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property User() As String
            Get
                Return ResourceManager.GetString("User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse.
        '''</summary>
        Friend Shared ReadOnly Property Warehouse() As String
            Get
                Return ResourceManager.GetString("Warehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Transfer.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseTransfer() As String
            Get
                Return ResourceManager.GetString("WarehouseTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WO Issuance.
        '''</summary>
        Friend Shared ReadOnly Property WOIssuance() As String
            Get
                Return ResourceManager.GetString("WOIssuance", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
