'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SABBPlugin.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Book set to default successfully.
        '''</summary>
        Friend Shared ReadOnly Property AfterDefault() As String
            Get
                Return ResourceManager.GetString("AfterDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image deleted successfully.
        '''</summary>
        Friend Shared ReadOnly Property AfterDeleteImg() As String
            Get
                Return ResourceManager.GetString("AfterDeleteImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Order approved.
        '''</summary>
        Friend Shared ReadOnly Property Approved() As String
            Get
                Return ResourceManager.GetString("Approved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select assets .
        '''</summary>
        Friend Shared ReadOnly Property AssetBCodeError() As String
            Get
                Return ResourceManager.GetString("AssetBCodeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets can&apos;t be transferred to this level, because &quot;Asset Category Min Level&quot; Parameter is bigger..
        '''</summary>
        Friend Shared ReadOnly Property AssetCategoryminlevel() As String
            Get
                Return ResourceManager.GetString("AssetCategoryminlevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset must be selected .
        '''</summary>
        Friend Shared ReadOnly Property AssetFirst() As String
            Get
                Return ResourceManager.GetString("AssetFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets can&apos;t be transferred to this level, because &quot;Asset Location Min Level&quot; Parameter is bigger..
        '''</summary>
        Friend Shared ReadOnly Property AssetlocationMinlevel() As String
            Get
                Return ResourceManager.GetString("AssetlocationMinlevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset not found, please try again.
        '''</summary>
        Friend Shared ReadOnly Property AssetNotFound() As String
            Get
                Return ResourceManager.GetString("AssetNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset transferred successfully.
        '''</summary>
        Friend Shared ReadOnly Property AssetTransferred() As String
            Get
                Return ResourceManager.GetString("AssetTransferred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset cannot be transferred in same Company.
        '''</summary>
        Friend Shared ReadOnly Property AstSameCompError() As String
            Get
                Return ResourceManager.GetString("AstSameCompError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select at least one book.
        '''</summary>
        Friend Shared ReadOnly Property AtLeastBook() As String
            Get
                Return ResourceManager.GetString("AtLeastBook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There must be at least one item in Purchase Order.
        '''</summary>
        Friend Shared ReadOnly Property AtLeastPOError() As String
            Get
                Return ResourceManager.GetString("AtLeastPOError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to save additional cost?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeAddAdditionalCost() As String
            Get
                Return ResourceManager.GetString("BeforeAddAdditionalCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to Approve ?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeApproved() As String
            Get
                Return ResourceManager.GetString("BeforeApproved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Book needs to be added.
        '''</summary>
        Friend Shared ReadOnly Property BeforeBookAdd() As String
            Get
                Return ResourceManager.GetString("BeforeBookAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Book needs to be updated.
        '''</summary>
        Friend Shared ReadOnly Property BeforeBookUpdate() As String
            Get
                Return ResourceManager.GetString("BeforeBookUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to set Book default ?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeDefault() As String
            Get
                Return ResourceManager.GetString("BeforeDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company have related assets, do you really want to delete this record ?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeDeleteCompanyHaveAsset() As String
            Get
                Return ResourceManager.GetString("BeforeDeleteCompanyHaveAsset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to delete this record ?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeDeleted() As String
            Get
                Return ResourceManager.GetString("BeforeDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleting this Asset will delete all its Depreciation and transfer history , Do you want to continue.
        '''</summary>
        Friend Shared ReadOnly Property BeforeDeletedAsset() As String
            Get
                Return ResourceManager.GetString("BeforeDeletedAsset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to delete this image ?.
        '''</summary>
        Friend Shared ReadOnly Property BeforeDeletedImg() As String
            Get
                Return ResourceManager.GetString("BeforeDeletedImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you really want to apply BarCode Structure.
        '''</summary>
        Friend Shared ReadOnly Property BeforePolicyApply() As String
            Get
                Return ResourceManager.GetString("BeforePolicyApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Book already closed for this date.
        '''</summary>
        Friend Shared ReadOnly Property BookAlreadyClosed() As String
            Get
                Return ResourceManager.GetString("BookAlreadyClosed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to close the report wizard?.
        '''</summary>
        Friend Shared ReadOnly Property CancelReport() As String
            Get
                Return ResourceManager.GetString("CancelReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset can not be copied if it is disposed.
        '''</summary>
        Friend Shared ReadOnly Property CanNotCopyDisposes() As String
            Get
                Return ResourceManager.GetString("CanNotCopyDisposes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please save before making the copy.
        '''</summary>
        Friend Shared ReadOnly Property CanNotCopyNotSavedAssets() As String
            Get
                Return ResourceManager.GetString("CanNotCopyNotSavedAssets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset can not be transferred if it is disposed.
        '''</summary>
        Friend Shared ReadOnly Property CanNotTransferDisposes() As String
            Get
                Return ResourceManager.GetString("CanNotTransferDisposes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot change Additional Cost after Depreciation is made.
        '''</summary>
        Friend Shared ReadOnly Property CantChangeAdditionalCost() As String
            Get
                Return ResourceManager.GetString("CantChangeAdditionalCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This record cannot be deleted as related records exists..
        '''</summary>
        Friend Shared ReadOnly Property CantDelete() As String
            Get
                Return ResourceManager.GetString("CantDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete Additional Cost after Depreciation is made.
        '''</summary>
        Friend Shared ReadOnly Property CantDeleteAdditionalCost() As String
            Get
                Return ResourceManager.GetString("CantDeleteAdditionalCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category code already exist in the same level..
        '''</summary>
        Friend Shared ReadOnly Property CatCodeAlreadyExist() As String
            Get
                Return ResourceManager.GetString("CatCodeAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category description already exist in the same level..
        '''</summary>
        Friend Shared ReadOnly Property CatDescAlreadyExist() As String
            Get
                Return ResourceManager.GetString("CatDescAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets images cleared successfully.
        '''</summary>
        Friend Shared ReadOnly Property ClearAstImgSucc() As String
            Get
                Return ResourceManager.GetString("ClearAstImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items images cleared successfully.
        '''</summary>
        Friend Shared ReadOnly Property ClearItmImgSucc() As String
            Get
                Return ResourceManager.GetString("ClearItmImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closed Ranges cannot be deleted or updated.
        '''</summary>
        Friend Shared ReadOnly Property ClosedCannotDelete() As String
            Get
                Return ResourceManager.GetString("ClosedCannotDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Role must have access on at least on Company.
        '''</summary>
        Friend Shared ReadOnly Property CompAccess() As String
            Get
                Return ResourceManager.GetString("CompAccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete the selected company, because there are related asset records or book records to it..
        '''</summary>
        Friend Shared ReadOnly Property CompanyRelatedRecords() As String
            Get
                Return ResourceManager.GetString("CompanyRelatedRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to process the selected assets data?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmProcessData() As String
            Get
                Return ResourceManager.GetString("ConfirmProcessData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are sure to send the data to the selected device, all data on the device will be replaced?.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmSendData() As String
            Get
                Return ResourceManager.GetString("ConfirmSendData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset Number must be between 1 and 100.
        '''</summary>
        Friend Shared ReadOnly Property CopyLimit() As String
            Get
                Return ResourceManager.GetString("CopyLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid database login information.
        '''</summary>
        Friend Shared ReadOnly Property DBLoginFail() As String
            Get
                Return ResourceManager.GetString("DBLoginFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please define Depreciation Policy for this category.
        '''</summary>
        Friend Shared ReadOnly Property DefinePolicy() As String
            Get
                Return ResourceManager.GetString("DefinePolicy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets Range for this company must be defined first.
        '''</summary>
        Friend Shared ReadOnly Property DefineRange() As String
            Get
                Return ResourceManager.GetString("DefineRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record deleted successfully.
        '''</summary>
        Friend Shared ReadOnly Property Deleted() As String
            Get
                Return ResourceManager.GetString("Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Evaluation, Assets Count exceed 10, Application will close now..
        '''</summary>
        Friend Shared ReadOnly Property DemoAssetCount() As String
            Get
                Return ResourceManager.GetString("DemoAssetCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are switching to Auto - Depreciation Mode .
        '''</summary>
        Friend Shared ReadOnly Property DepRuntoAuto() As String
            Get
                Return ResourceManager.GetString("DepRuntoAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are switching to Manual - Depreciation Mode.
        '''</summary>
        Friend Shared ReadOnly Property DepRuntoMan() As String
            Get
                Return ResourceManager.GetString("DepRuntoMan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount cannot exeed the total amount..
        '''</summary>
        Friend Shared ReadOnly Property DiscountExeed() As String
            Get
                Return ResourceManager.GetString("DiscountExeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Group ID exist please try again.
        '''</summary>
        Friend Shared ReadOnly Property DuplicompGroup() As String
            Get
                Return ResourceManager.GetString("DuplicompGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allowed barcode size exceeded.
        '''</summary>
        Friend Shared ReadOnly Property ExceedBarCode() As String
            Get
                Return ResourceManager.GetString("ExceedBarCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets images exported successfully.
        '''</summary>
        Friend Shared ReadOnly Property ExportAstImgSucc() As String
            Get
                Return ResourceManager.GetString("ExportAstImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items images exported successfully.
        '''</summary>
        Friend Shared ReadOnly Property ExportItmImgSucc() As String
            Get
                Return ResourceManager.GetString("ExportItmImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assets images imported successfully.
        '''</summary>
        Friend Shared ReadOnly Property ImportAstImgSucc() As String
            Get
                Return ResourceManager.GetString("ImportAstImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items images imported successfully.
        '''</summary>
        Friend Shared ReadOnly Property ImportItmImgSucc() As String
            Get
                Return ResourceManager.GetString("ImportItmImgSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid resgistration key !.
        '''</summary>
        Friend Shared ReadOnly Property InValid() As String
            Get
                Return ResourceManager.GetString("InValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter valid Asset Number.
        '''</summary>
        Friend Shared ReadOnly Property InvalidAstNum() As String
            Get
                Return ResourceManager.GetString("InvalidAstNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid current book value .
        '''</summary>
        Friend Shared ReadOnly Property InvalidCBV() As String
            Get
                Return ResourceManager.GetString("InvalidCBV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost must be greater then zero.
        '''</summary>
        Friend Shared ReadOnly Property InvalidCost() As String
            Get
                Return ResourceManager.GetString("InvalidCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter valid database information.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDB() As String
            Get
                Return ResourceManager.GetString("InvalidDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid month.
        '''</summary>
        Friend Shared ReadOnly Property InvalidMonth() As String
            Get
                Return ResourceManager.GetString("InvalidMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter valid number.
        '''</summary>
        Friend Shared ReadOnly Property InvalidNum() As String
            Get
                Return ResourceManager.GetString("InvalidNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prefix cannot be LOC.
        '''</summary>
        Friend Shared ReadOnly Property InvalidPrefix() As String
            Get
                Return ResourceManager.GetString("InvalidPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Serial cannot be greater than End Serial.
        '''</summary>
        Friend Shared ReadOnly Property InvalidRange() As String
            Get
                Return ResourceManager.GetString("InvalidRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid registration found.
        '''</summary>
        Friend Shared ReadOnly Property InvalidRegisfound() As String
            Get
                Return ResourceManager.GetString("InvalidRegisfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select Location.
        '''</summary>
        Friend Shared ReadOnly Property LocBCodeError() As String
            Get
                Return ResourceManager.GetString("LocBCodeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location code already exist in the same level..
        '''</summary>
        Friend Shared ReadOnly Property LocCodeAlreadyExist() As String
            Get
                Return ResourceManager.GetString("LocCodeAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location description already exist in the same level..
        '''</summary>
        Friend Shared ReadOnly Property LocDescAlreadyExist() As String
            Get
                Return ResourceManager.GetString("LocDescAlreadyExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There can be max. 10 levels of Hierarchy.
        '''</summary>
        Friend Shared ReadOnly Property MaxTreeLevel() As String
            Get
                Return ResourceManager.GetString("MaxTreeLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Asset Book associated with selected company, Asset cannot be saved..
        '''</summary>
        Friend Shared ReadOnly Property NoCompanyBookSelected() As String
            Get
                Return ResourceManager.GetString("NoCompanyBookSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anonymous Asset is successfully registered.
        '''</summary>
        Friend Shared ReadOnly Property NonTranSuccess() As String
            Get
                Return ResourceManager.GetString("NonTranSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Record(s) selected..
        '''</summary>
        Friend Shared ReadOnly Property NoRecordSelected() As String
            Get
                Return ResourceManager.GetString("NoRecordSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No selected assets, please select some assets and try again..
        '''</summary>
        Friend Shared ReadOnly Property NoSelectedAssets() As String
            Get
                Return ResourceManager.GetString("NoSelectedAssets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a numeric value.
        '''</summary>
        Friend Shared ReadOnly Property NotDigit() As String
            Get
                Return ResourceManager.GetString("NotDigit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record can&apos;t be saved, check the fields that have error and try again..
        '''</summary>
        Friend Shared ReadOnly Property NotSaved() As String
            Get
                Return ResourceManager.GetString("NotSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid old password, try again..
        '''</summary>
        Friend Shared ReadOnly Property OldPasswordNotCorrect() As String
            Get
                Return ResourceManager.GetString("OldPasswordNotCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entered value is out of percentage range(1,1200).
        '''</summary>
        Friend Shared ReadOnly Property OutPercentRange() As String
            Get
                Return ResourceManager.GetString("OutPercentRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password and Confirm Password must be same.
        '''</summary>
        Friend Shared ReadOnly Property PasswordAndConfirmNotMatched() As String
            Get
                Return ResourceManager.GetString("PasswordAndConfirmNotMatched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password Changed Successfully..
        '''</summary>
        Friend Shared ReadOnly Property PasswordChangedSucc() As String
            Get
                Return ResourceManager.GetString("PasswordChangedSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purcahse Order is completely tansfered successfully.
        '''</summary>
        Friend Shared ReadOnly Property PoCompTransfer() As String
            Get
                Return ResourceManager.GetString("PoCompTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made to PartialReceived and Received PO..
        '''</summary>
        Friend Shared ReadOnly Property PONoChange() As String
            Get
                Return ResourceManager.GetString("PONoChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process Completed..
        '''</summary>
        Friend Shared ReadOnly Property ProcessComplete() As String
            Get
                Return ResourceManager.GetString("ProcessComplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Date should be less than Service Date, change it and try again.
        '''</summary>
        Friend Shared ReadOnly Property PurchaseDateShouldBeLessThanServiceDate() As String
            Get
                Return ResourceManager.GetString("PurchaseDateShouldBeLessThanServiceDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Range already exists for this company.
        '''</summary>
        Friend Shared ReadOnly Property RangeComExist() As String
            Get
                Return ResourceManager.GetString("RangeComExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial Range exceeded for this company, please define new range.
        '''</summary>
        Friend Shared ReadOnly Property RangeExceedCreateNew() As String
            Get
                Return ResourceManager.GetString("RangeExceedCreateNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Range already exists.
        '''</summary>
        Friend Shared ReadOnly Property RangeExist() As String
            Get
                Return ResourceManager.GetString("RangeExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oracle reference ID exists !.
        '''</summary>
        Friend Shared ReadOnly Property RefIDExist() As String
            Get
                Return ResourceManager.GetString("RefIDExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report not found!, restore all reports from Report Designer first..
        '''</summary>
        Friend Shared ReadOnly Property ReportNotFound() As String
            Get
                Return ResourceManager.GetString("ReportNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset cannot be transferred in same company.
        '''</summary>
        Friend Shared ReadOnly Property SameCoError() As String
            Get
                Return ResourceManager.GetString("SameCoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record saved successfully.
        '''</summary>
        Friend Shared ReadOnly Property Saved() As String
            Get
                Return ResourceManager.GetString("Saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select device .
        '''</summary>
        Friend Shared ReadOnly Property SelectDevice() As String
            Get
                Return ResourceManager.GetString("SelectDevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select one option first..
        '''</summary>
        Friend Shared ReadOnly Property SelectOptionFirst() As String
            Get
                Return ResourceManager.GetString("SelectOptionFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select report from the left side, and try again!..
        '''</summary>
        Friend Shared ReadOnly Property SelectReportFirst() As String
            Get
                Return ResourceManager.GetString("SelectReportFirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select tranfser method.
        '''</summary>
        Friend Shared ReadOnly Property SelectTranfer() As String
            Get
                Return ResourceManager.GetString("SelectTranfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select item to transfer.
        '''</summary>
        Friend Shared ReadOnly Property SelectTransItem() As String
            Get
                Return ResourceManager.GetString("SelectTransItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error reported successfully, You will be contacted shortly.
        '''</summary>
        Friend Shared ReadOnly Property SendErConfrm() As String
            Get
                Return ResourceManager.GetString("SendErConfrm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internet connection could not be found .
        '''</summary>
        Friend Shared ReadOnly Property SendErrError() As String
            Get
                Return ResourceManager.GetString("SendErrError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System setting updated successfully.
        '''</summary>
        Friend Shared ReadOnly Property Settingupdated() As String
            Get
                Return ResourceManager.GetString("Settingupdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory End Date cannot be earlier than Start Date.
        '''</summary>
        Friend Shared ReadOnly Property StartEndDate() As String
            Get
                Return ResourceManager.GetString("StartEndDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System values cannot be deleted.
        '''</summary>
        Friend Shared ReadOnly Property SystemValueDeleted() As String
            Get
                Return ResourceManager.GetString("SystemValueDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System values cannot be edited.
        '''</summary>
        Friend Shared ReadOnly Property SystemValueEdit() As String
            Get
                Return ResourceManager.GetString("SystemValueEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanned asset barcode does not belong to the selected location. Do you want to transfer the asset?.
        '''</summary>
        Friend Shared ReadOnly Property TransferAssetConfirm() As String
            Get
                Return ResourceManager.GetString("TransferAssetConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a value before transfer.
        '''</summary>
        Friend Shared ReadOnly Property TransferReqInfo() As String
            Get
                Return ResourceManager.GetString("TransferReqInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asset cannot be Transferred with same information.
        '''</summary>
        Friend Shared ReadOnly Property TransferSame() As String
            Get
                Return ResourceManager.GetString("TransferSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Login Name or Password.
        '''</summary>
        Friend Shared ReadOnly Property UserLoginFail() As String
            Get
                Return ResourceManager.GetString("UserLoginFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter Login Name and Password.
        '''</summary>
        Friend Shared ReadOnly Property UserLoginMandatory() As String
            Get
                Return ResourceManager.GetString("UserLoginMandatory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ZulAsset registered successfully.
        '''</summary>
        Friend Shared ReadOnly Property ValidKey() As String
            Get
                Return ResourceManager.GetString("ValidKey", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
