'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SABBPlugin.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to add missing items..
        '''</summary>
        Friend Shared ReadOnly Property AddMissingItems() As String
            Get
                Return ResourceManager.GetString("AddMissingItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to assign customers to seleceted  route ?.
        '''</summary>
        Friend Shared ReadOnly Property AssignRouteConfirm() As String
            Get
                Return ResourceManager.GetString("AssignRouteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Barcode length must be greater than the sum of (IdentifierLength+PLULength+TokenLength).
        '''</summary>
        Friend Shared ReadOnly Property BarcodelengthNotValid() As String
            Get
                Return ResourceManager.GetString("BarcodelengthNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All the barcodes has been defined in specified range.
        '''</summary>
        Friend Shared ReadOnly Property BarcodeRange() As String
            Get
                Return ResourceManager.GetString("BarcodeRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Approve.
        '''</summary>
        Friend Shared ReadOnly Property btnApproveCaption() As String
            Get
                Return ResourceManager.GetString("btnApproveCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Change Password.
        '''</summary>
        Friend Shared ReadOnly Property btnChangePassCaption() As String
            Get
                Return ResourceManager.GetString("btnChangePassCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Selected User Password.
        '''</summary>
        Friend Shared ReadOnly Property btnChangePassHint() As String
            Get
                Return ResourceManager.GetString("btnChangePassHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receive Items.
        '''</summary>
        Friend Shared ReadOnly Property btnDOReceiving() As String
            Get
                Return ResourceManager.GetString("btnDOReceiving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close PO.
        '''</summary>
        Friend Shared ReadOnly Property btnPOClosing() As String
            Get
                Return ResourceManager.GetString("btnPOClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reopen.
        '''</summary>
        Friend Shared ReadOnly Property btnPOOpen() As String
            Get
                Return ResourceManager.GetString("btnPOOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post.
        '''</summary>
        Friend Shared ReadOnly Property btnPostCaption() As String
            Get
                Return ResourceManager.GetString("btnPostCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reject.
        '''</summary>
        Friend Shared ReadOnly Property btnReject() As String
            Get
                Return ResourceManager.GetString("btnReject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return.
        '''</summary>
        Friend Shared ReadOnly Property btnReturn() As String
            Get
                Return ResourceManager.GetString("btnReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close WO.
        '''</summary>
        Friend Shared ReadOnly Property btnWOClosing() As String
            Get
                Return ResourceManager.GetString("btnWOClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Issue Items.
        '''</summary>
        Friend Shared ReadOnly Property btnWOIssuing() As String
            Get
                Return ResourceManager.GetString("btnWOIssuing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reopen.
        '''</summary>
        Friend Shared ReadOnly Property btnWOOpen() As String
            Get
                Return ResourceManager.GetString("btnWOOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can not logout from the application, please close all opened forms and try again!..
        '''</summary>
        Friend Shared ReadOnly Property CanNotLogout() As String
            Get
                Return ResourceManager.GetString("CanNotLogout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to clear all data?.
        '''</summary>
        Friend Shared ReadOnly Property ClearDatabase() As String
            Get
                Return ResourceManager.GetString("ClearDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to create PO for the selected Items?.
        '''</summary>
        Friend Shared ReadOnly Property CreatePOConfirmation() As String
            Get
                Return ResourceManager.GetString("CreatePOConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All data will be lost.Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property DataLoss() As String
            Get
                Return ResourceManager.GetString("DataLoss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No data found for the selected date and filtration..
        '''</summary>
        Friend Shared ReadOnly Property DataNotFound() As String
            Get
                Return ResourceManager.GetString("DataNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.xml file not found in the application path..
        '''</summary>
        Friend Shared ReadOnly Property DataxmlNotFound() As String
            Get
                Return ResourceManager.GetString("DataxmlNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter database Parameters.
        '''</summary>
        Friend Shared ReadOnly Property DBParameters() As String
            Get
                Return ResourceManager.GetString("DBParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decimal Positions must be less than Token Length.
        '''</summary>
        Friend Shared ReadOnly Property DecimalPositionsNotValid() As String
            Get
                Return ResourceManager.GetString("DecimalPositionsNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to delete company settings({0})?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteDatabaseSettings() As String
            Get
                Return ResourceManager.GetString("DeleteDatabaseSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to delete route customer ?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteRouteCustomer() As String
            Get
                Return ResourceManager.GetString("DeleteRouteCustomer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete all transactions?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteTransaction() As String
            Get
                Return ResourceManager.GetString("DeleteTransaction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This warehouse already has prepared inventory,first post that inventory..
        '''</summary>
        Friend Shared ReadOnly Property DeselectInventoryWarehouse() As String
            Get
                Return ResourceManager.GetString("DeselectInventoryWarehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount should be equal or greater than 0..
        '''</summary>
        Friend Shared ReadOnly Property DiscountEqualOrGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("DiscountEqualOrGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter Lot Numbers for lot items..
        '''</summary>
        Friend Shared ReadOnly Property EnterLotNumber() As String
            Get
                Return ResourceManager.GetString("EnterLotNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter Serial Numbers for serialized items..
        '''</summary>
        Friend Shared ReadOnly Property EnterSerialNumber() As String
            Get
                Return ResourceManager.GetString("EnterSerialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while importing report.
        '''</summary>
        Friend Shared ReadOnly Property ErrorImportingReport() As String
            Get
                Return ResourceManager.GetString("ErrorImportingReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From/To Locations should not be same..
        '''</summary>
        Friend Shared ReadOnly Property FromToLocationsSame() As String
            Get
                Return ResourceManager.GetString("FromToLocationsSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From and To warehouse must be different from each others..
        '''</summary>
        Friend Shared ReadOnly Property FromToWarehouseSame() As String
            Get
                Return ResourceManager.GetString("FromToWarehouseSame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to generate GTN ?.
        '''</summary>
        Friend Shared ReadOnly Property GenerateGTN() As String
            Get
                Return ResourceManager.GetString("GenerateGTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get report data....
        '''</summary>
        Friend Shared ReadOnly Property GetReportData() As String
            Get
                Return ResourceManager.GetString("GetReportData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Data - Please Wait....
        '''</summary>
        Friend Shared ReadOnly Property GettingData() As String
            Get
                Return ResourceManager.GetString("GettingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help file not found in the following path.
        '''</summary>
        Friend Shared ReadOnly Property HelpFileNotFound() As String
            Get
                Return ResourceManager.GetString("HelpFileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will overwrite all reports have the same name, are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property ImportsReports() As String
            Get
                Return ResourceManager.GetString("ImportsReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid license key..
        '''</summary>
        Friend Shared ReadOnly Property InvalidLicenseKey() As String
            Get
                Return ResourceManager.GetString("InvalidLicenseKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory must contain at least one item..
        '''</summary>
        Friend Shared ReadOnly Property InventoryItem() As String
            Get
                Return ResourceManager.GetString("InventoryItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once Inventory is posted. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property InventoryPost() As String
            Get
                Return ResourceManager.GetString("InventoryPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot modify.Inventory already posted..
        '''</summary>
        Friend Shared ReadOnly Property InventoryPosted() As String
            Get
                Return ResourceManager.GetString("InventoryPosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice must contain at least one item..
        '''</summary>
        Friend Shared ReadOnly Property InvoiceItem() As String
            Get
                Return ResourceManager.GetString("InvoiceItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once invoice is posted. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property InvoicePost() As String
            Get
                Return ResourceManager.GetString("InvoicePost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot modify.Invoice already posted..
        '''</summary>
        Friend Shared ReadOnly Property InvoicePosted() As String
            Get
                Return ResourceManager.GetString("InvoicePosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure want to return invoice?.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceReturn() As String
            Get
                Return ResourceManager.GetString("InvoiceReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item already existed in the grid..
        '''</summary>
        Friend Shared ReadOnly Property ItemAlreadyExisted() As String
            Get
                Return ResourceManager.GetString("ItemAlreadyExisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item does not exist..
        '''</summary>
        Friend Shared ReadOnly Property ItemDoesntExist() As String
            Get
                Return ResourceManager.GetString("ItemDoesntExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Requires Price Update..
        '''</summary>
        Friend Shared ReadOnly Property ItemRequiredPriceUpdate() As String
            Get
                Return ResourceManager.GetString("ItemRequiredPriceUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select item first..
        '''</summary>
        Friend Shared ReadOnly Property ItemsNotSelected() As String
            Get
                Return ResourceManager.GetString("ItemsNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0}) Prices will be discarded, are you sure to continue?.
        '''</summary>
        Friend Shared ReadOnly Property ItemUpdatePriceDiscard() As String
            Get
                Return ResourceManager.GetString("ItemUpdatePriceDiscard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0}) Prices will be posted, are you sure to continue?.
        '''</summary>
        Friend Shared ReadOnly Property ItemUpdatePricePost() As String
            Get
                Return ResourceManager.GetString("ItemUpdatePricePost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language has been changed, Please run the application again..
        '''</summary>
        Friend Shared ReadOnly Property LanguageChangedRestart() As String
            Get
                Return ResourceManager.GetString("LanguageChangedRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Data. Please Wait..
        '''</summary>
        Friend Shared ReadOnly Property LoadingData() As String
            Get
                Return ResourceManager.GetString("LoadingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure that you want to logout? all opened forms will be closed..
        '''</summary>
        Friend Shared ReadOnly Property LogoutConfrim() As String
            Get
                Return ResourceManager.GetString("LogoutConfrim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to logout from the application, please close all the forms and try again..
        '''</summary>
        Friend Shared ReadOnly Property LogoutFailed() As String
            Get
                Return ResourceManager.GetString("LogoutFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot post.No items are requested,add items and try again..
        '''</summary>
        Friend Shared ReadOnly Property NoItemsRequested() As String
            Get
                Return ResourceManager.GetString("NoItemsRequested", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot post.Please review transfer quantity of all items.It cannot be zero..
        '''</summary>
        Friend Shared ReadOnly Property NoQTY() As String
            Get
                Return ResourceManager.GetString("NoQTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No record(s) selected..
        '''</summary>
        Friend Shared ReadOnly Property NoRecord() As String
            Get
                Return ResourceManager.GetString("NoRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient Permission, current logged in user is not authorized to perform this action..
        '''</summary>
        Friend Shared ReadOnly Property NotAuthorized() As String
            Get
                Return ResourceManager.GetString("NotAuthorized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Password not correct!..
        '''</summary>
        Friend Shared ReadOnly Property OldPasswordNotCorrect() As String
            Get
                Return ResourceManager.GetString("OldPasswordNotCorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Document..
        '''</summary>
        Friend Shared ReadOnly Property OpenDocument() As String
            Get
                Return ResourceManager.GetString("OpenDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Item Card..
        '''</summary>
        Friend Shared ReadOnly Property OpenItemCard() As String
            Get
                Return ResourceManager.GetString("OpenItemCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once order is canceled.Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property OrderCancel() As String
            Get
                Return ResourceManager.GetString("OrderCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to close the PO again?.
        '''</summary>
        Friend Shared ReadOnly Property OrderClose() As String
            Get
                Return ResourceManager.GetString("OrderClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once order is approved. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property OrderConfirm() As String
            Get
                Return ResourceManager.GetString("OrderConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order must contain at least one item.
        '''</summary>
        Friend Shared ReadOnly Property OrderItemsNotFound() As String
            Get
                Return ResourceManager.GetString("OrderItemsNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Request must be approved for further process.
        '''</summary>
        Friend Shared ReadOnly Property OrderMustApproved() As String
            Get
                Return ResourceManager.GetString("OrderMustApproved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to open the PO again?.
        '''</summary>
        Friend Shared ReadOnly Property OrderOpen() As String
            Get
                Return ResourceManager.GetString("OrderOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot modify. Order already posted..
        '''</summary>
        Friend Shared ReadOnly Property OrderPosted() As String
            Get
                Return ResourceManager.GetString("OrderPosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The parent must be diffrent from the current item..
        '''</summary>
        Friend Shared ReadOnly Property ParentMustBeDifferent() As String
            Get
                Return ResourceManager.GetString("ParentMustBeDifferent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password Changed Successfully..
        '''</summary>
        Friend Shared ReadOnly Property PasswordChangedSucc() As String
            Get
                Return ResourceManager.GetString("PasswordChangedSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password was not correctly confirmed.  Please ensure that the password and confirmation match exactly..
        '''</summary>
        Friend Shared ReadOnly Property Passwordnotverified() As String
            Get
                Return ResourceManager.GetString("Passwordnotverified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PKG Type not found in any SKU related to this item, first add SKU with the same PKG and then try again.
        '''</summary>
        Friend Shared ReadOnly Property PKGNotFound() As String
            Get
                Return ResourceManager.GetString("PKGNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Wait.....
        '''</summary>
        Friend Shared ReadOnly Property PleaseWait() As String
            Get
                Return ResourceManager.GetString("PleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLU Start must be more than Identifier length.
        '''</summary>
        Friend Shared ReadOnly Property PLUStartNotValid() As String
            Get
                Return ResourceManager.GetString("PLUStartNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO with code({0}) created successfully, please navigate to PO to complete the information..
        '''</summary>
        Friend Shared ReadOnly Property POCreatedSuccessfully() As String
            Get
                Return ResourceManager.GetString("POCreatedSuccessfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating report..
        '''</summary>
        Friend Shared ReadOnly Property PopulateReport() As String
            Get
                Return ResourceManager.GetString("PopulateReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All serial numbers must be entered..
        '''</summary>
        Friend Shared ReadOnly Property PreventEmptySerialNumber() As String
            Get
                Return ResourceManager.GetString("PreventEmptySerialNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price should be equal or greater than 0..
        '''</summary>
        Friend Shared ReadOnly Property PriceEqualOrGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("PriceEqualOrGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price should be greater than 0..
        '''</summary>
        Friend Shared ReadOnly Property PriceGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to update the the price for all items?.
        '''</summary>
        Friend Shared ReadOnly Property PriceUpdateConfirm() As String
            Get
                Return ResourceManager.GetString("PriceUpdateConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item(s) price updated successfully..
        '''</summary>
        Friend Shared ReadOnly Property PriceUpdatedSuccessfully() As String
            Get
                Return ResourceManager.GetString("PriceUpdatedSuccessfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Labels for {0} {1} will be printed. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property PrintLabelConfirm() As String
            Get
                Return ResourceManager.GetString("PrintLabelConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to print?.
        '''</summary>
        Friend Shared ReadOnly Property PrintReportConfirmation() As String
            Get
                Return ResourceManager.GetString("PrintReportConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Processing Request....
        '''</summary>
        Friend Shared ReadOnly Property ProcessingRequest() As String
            Get
                Return ResourceManager.GetString("ProcessingRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure that you process the selected Unknown Barcode?.
        '''</summary>
        Friend Shared ReadOnly Property ProcessUnknownBarcodeConfirm() As String
            Get
                Return ResourceManager.GetString("ProcessUnknownBarcodeConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quantity.
        '''</summary>
        Friend Shared ReadOnly Property QTY() As String
            Get
                Return ResourceManager.GetString("QTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QTY should be greater than 0..
        '''</summary>
        Friend Shared ReadOnly Property QTYCreaterThanZero() As String
            Get
                Return ResourceManager.GetString("QTYCreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once receipt is posted. Do you want to continue.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptPost() As String
            Get
                Return ResourceManager.GetString("ReceiptPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot save. Receipt already posted.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptPosted() As String
            Get
                Return ResourceManager.GetString("ReceiptPosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records has been deleted successfully..
        '''</summary>
        Friend Shared ReadOnly Property RecordsDeleted() As String
            Get
                Return ResourceManager.GetString("RecordsDeleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report({0}) not found in database, please restore or import the report from Tools-&gt;Report Designer and try again..
        '''</summary>
        Friend Shared ReadOnly Property ReportNotFound() As String
            Get
                Return ResourceManager.GetString("ReportNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No sales order(s) to process.
        '''</summary>
        Friend Shared ReadOnly Property RequestOrders() As String
            Get
                Return ResourceManager.GetString("RequestOrders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The restoration of all the reports has been successful..
        '''</summary>
        Friend Shared ReadOnly Property RestoreAllReports() As String
            Get
                Return ResourceManager.GetString("RestoreAllReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to restore data.  Check that the file selected is accessible..
        '''</summary>
        Friend Shared ReadOnly Property RestoreBackupFailed() As String
            Get
                Return ResourceManager.GetString("RestoreBackupFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore process will undo all the changes made by the user in report(s) {0} Do you still want to restore the orginal report(s)?.
        '''</summary>
        Friend Shared ReadOnly Property RestoreProcess() As String
            Get
                Return ResourceManager.GetString("RestoreProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The restoration of the report was successful..
        '''</summary>
        Friend Shared ReadOnly Property RestoreReports() As String
            Get
                Return ResourceManager.GetString("RestoreReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select From and To Date..
        '''</summary>
        Friend Shared ReadOnly Property SelectDate() As String
            Get
                Return ResourceManager.GetString("SelectDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select document number..
        '''</summary>
        Friend Shared ReadOnly Property SelectDoc() As String
            Get
                Return ResourceManager.GetString("SelectDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select inventory first..
        '''</summary>
        Friend Shared ReadOnly Property SelectInventory() As String
            Get
                Return ResourceManager.GetString("SelectInventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select item first..
        '''</summary>
        Friend Shared ReadOnly Property SelectItem() As String
            Get
                Return ResourceManager.GetString("SelectItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select items from below grid first..
        '''</summary>
        Friend Shared ReadOnly Property SelectItemsFromGrid() As String
            Get
                Return ResourceManager.GetString("SelectItemsFromGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select session first..
        '''</summary>
        Friend Shared ReadOnly Property SelectSession() As String
            Get
                Return ResourceManager.GetString("SelectSession", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select warehouse before scaning/selecting items..
        '''</summary>
        Friend Shared ReadOnly Property SelectWarehouseBeforeScaning() As String
            Get
                Return ResourceManager.GetString("SelectWarehouseBeforeScaning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sessions not found in database..
        '''</summary>
        Friend Shared ReadOnly Property SessionsNotFound() As String
            Get
                Return ResourceManager.GetString("SessionsNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum Discount.
        '''</summary>
        Friend Shared ReadOnly Property SumDiscount() As String
            Get
                Return ResourceManager.GetString("SumDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Token Start must be more than Identifier length + PLU Length.
        '''</summary>
        Friend Shared ReadOnly Property TokenStartNotValid() As String
            Get
                Return ResourceManager.GetString("TokenStartNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total discount should be less or equal to sub total amount..
        '''</summary>
        Friend Shared ReadOnly Property TotalDiscountMoreThanTotalAmount() As String
            Get
                Return ResourceManager.GetString("TotalDiscountMoreThanTotalAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total should be equal or greater than 0..
        '''</summary>
        Friend Shared ReadOnly Property TotalEqualOrCreaterThanZero() As String
            Get
                Return ResourceManager.GetString("TotalEqualOrCreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All transactions will be lost.Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property TransactionLoss() As String
            Get
                Return ResourceManager.GetString("TransactionLoss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No changes can be made once transfer is posted. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property TransferPost() As String
            Get
                Return ResourceManager.GetString("TransferPost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot modify. Transfer already posted..
        '''</summary>
        Friend Shared ReadOnly Property TransferPosted() As String
            Get
                Return ResourceManager.GetString("TransferPosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer quantity cannot be greater than current quantity.
        '''</summary>
        Friend Shared ReadOnly Property TransferQty() As String
            Get
                Return ResourceManager.GetString("TransferQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock transfer created successfully.
        '''</summary>
        Friend Shared ReadOnly Property TransferSuccess() As String
            Get
                Return ResourceManager.GetString("TransferSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There may be other users logged into application.{0} You must kick them off immediately before proceed with the database upgrade. {0}Are you sure you want to update the database?.
        '''</summary>
        Friend Shared ReadOnly Property UpdateDatabaseConfirm() As String
            Get
                Return ResourceManager.GetString("UpdateDatabaseConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error when doing DBUpdate..
        '''</summary>
        Friend Shared ReadOnly Property UpdateDatabaseError() As String
            Get
                Return ResourceManager.GetString("UpdateDatabaseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your copy of {0} Application has been updated, your database must be updated as well to be able to open it..
        '''</summary>
        Friend Shared ReadOnly Property UpdateDatabaseMessage() As String
            Get
                Return ResourceManager.GetString("UpdateDatabaseMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating database is required, you can not skip updating database, Please try again..
        '''</summary>
        Friend Shared ReadOnly Property UpdateDatabaseRequired() As String
            Get
                Return ResourceManager.GetString("UpdateDatabaseRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating database.  Might take a few minutes....
        '''</summary>
        Friend Shared ReadOnly Property UpdatingDatabase() As String
            Get
                Return ResourceManager.GetString("UpdatingDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database updated successfully, you can continue with the login..
        '''</summary>
        Friend Shared ReadOnly Property UpdatingDatabaseSuccess() As String
            Get
                Return ResourceManager.GetString("UpdatingDatabaseSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value greater or equal zero..
        '''</summary>
        Friend Shared ReadOnly Property valRuleGreaterOrEqualZero() As String
            Get
                Return ResourceManager.GetString("valRuleGreaterOrEqualZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value greater than zero..
        '''</summary>
        Friend Shared ReadOnly Property valRuleGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("valRuleGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a positive value..
        '''</summary>
        Friend Shared ReadOnly Property valRuleNotContainMinus() As String
            Get
                Return ResourceManager.GetString("valRuleNotContainMinus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a value, Field must not be empty..
        '''</summary>
        Friend Shared ReadOnly Property valRulenotEmpty() As String
            Get
                Return ResourceManager.GetString("valRulenotEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select warehouse first..
        '''</summary>
        Friend Shared ReadOnly Property WarehouseNotSelected() As String
            Get
                Return ResourceManager.GetString("WarehouseNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Any data saved after the backup will be lost when restoring to an older backup file. Are you sure to continue?.
        '''</summary>
        Friend Shared ReadOnly Property Warning_RestoreBackup() As String
            Get
                Return ResourceManager.GetString("Warning_RestoreBackup", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
