'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ColsName
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SABBPlugin.ColsName", GetType(ColsName).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Details.
        '''</summary>
        Friend Shared ReadOnly Property AddressDetailsColumn() As String
            Get
                Return ResourceManager.GetString("AddressDetailsColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend Shared ReadOnly Property Amount() As String
            Get
                Return ResourceManager.GetString("Amount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArabicCaption.
        '''</summary>
        Friend Shared ReadOnly Property ArabicCaptionColumn() As String
            Get
                Return ResourceManager.GetString("ArabicCaptionColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArName.
        '''</summary>
        Friend Shared ReadOnly Property ArName() As String
            Get
                Return ResourceManager.GetString("ArName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available QTY.
        '''</summary>
        Friend Shared ReadOnly Property AvailableQTYColumn() As String
            Get
                Return ResourceManager.GetString("AvailableQTYColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Barcode.
        '''</summary>
        Friend Shared ReadOnly Property BarcodeColumn() As String
            Get
                Return ResourceManager.GetString("BarcodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category Ar Name.
        '''</summary>
        Friend Shared ReadOnly Property CategoryArName() As String
            Get
                Return ResourceManager.GetString("CategoryArName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category Name.
        '''</summary>
        Friend Shared ReadOnly Property CategoryEngColumn() As String
            Get
                Return ResourceManager.GetString("CategoryEngColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classification Name.
        '''</summary>
        Friend Shared ReadOnly Property ClassificationEngName() As String
            Get
                Return ResourceManager.GetString("ClassificationEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classification ArName.
        '''</summary>
        Friend Shared ReadOnly Property ClassificationName() As String
            Get
                Return ResourceManager.GetString("ClassificationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CloseAmount.
        '''</summary>
        Friend Shared ReadOnly Property CloseAmountColumn() As String
            Get
                Return ResourceManager.GetString("CloseAmountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CloseDateTime.
        '''</summary>
        Friend Shared ReadOnly Property CloseDateTimeColumn() As String
            Get
                Return ResourceManager.GetString("CloseDateTimeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Friend Shared ReadOnly Property Code() As String
            Get
                Return ResourceManager.GetString("Code", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ControlName.
        '''</summary>
        Friend Shared ReadOnly Property ControlNameColumn() As String
            Get
                Return ResourceManager.GetString("ControlNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property CreationDate() As String
            Get
                Return ResourceManager.GetString("CreationDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credit.
        '''</summary>
        Friend Shared ReadOnly Property CreditColumn() As String
            Get
                Return ResourceManager.GetString("CreditColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current QTY.
        '''</summary>
        Friend Shared ReadOnly Property CurrentQTYColumn() As String
            Get
                Return ResourceManager.GetString("CurrentQTYColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custodian.
        '''</summary>
        Friend Shared ReadOnly Property Custodian() As String
            Get
                Return ResourceManager.GetString("Custodian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Number.
        '''</summary>
        Friend Shared ReadOnly Property CustomerAccountNumber() As String
            Get
                Return ResourceManager.GetString("CustomerAccountNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Name.
        '''</summary>
        Friend Shared ReadOnly Property CustomerEngName() As String
            Get
                Return ResourceManager.GetString("CustomerEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer ArName.
        '''</summary>
        Friend Shared ReadOnly Property CustomerName() As String
            Get
                Return ResourceManager.GetString("CustomerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer Type.
        '''</summary>
        Friend Shared ReadOnly Property CustomerTypesEngName() As String
            Get
                Return ResourceManager.GetString("CustomerTypesEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer ArType.
        '''</summary>
        Friend Shared ReadOnly Property CustomerTypesName() As String
            Get
                Return ResourceManager.GetString("CustomerTypesName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debit.
        '''</summary>
        Friend Shared ReadOnly Property DebitColumn() As String
            Get
                Return ResourceManager.GetString("DebitColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeviceName.
        '''</summary>
        Friend Shared ReadOnly Property DeviceEngNameColumn() As String
            Get
                Return ResourceManager.GetString("DeviceEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Difference.
        '''</summary>
        Friend Shared ReadOnly Property DifferenceColumn() As String
            Get
                Return ResourceManager.GetString("DifferenceColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discount.
        '''</summary>
        Friend Shared ReadOnly Property Discount() As String
            Get
                Return ResourceManager.GetString("Discount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocType.
        '''</summary>
        Friend Shared ReadOnly Property DocTypeEngNameColumn() As String
            Get
                Return ResourceManager.GetString("DocTypeEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DocTypeAr.
        '''</summary>
        Friend Shared ReadOnly Property DocTypeNameColumn() As String
            Get
                Return ResourceManager.GetString("DocTypeNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property EmailColumn() As String
            Get
                Return ResourceManager.GetString("EmailColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emp Name.
        '''</summary>
        Friend Shared ReadOnly Property EmpEngName() As String
            Get
                Return ResourceManager.GetString("EmpEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emp ArName.
        '''</summary>
        Friend Shared ReadOnly Property EmpName() As String
            Get
                Return ResourceManager.GetString("EmpName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EngCaption.
        '''</summary>
        Friend Shared ReadOnly Property EngCaptionColumn() As String
            Get
                Return ResourceManager.GetString("EngCaptionColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EngName.
        '''</summary>
        Friend Shared ReadOnly Property EngName() As String
            Get
                Return ResourceManager.GetString("EngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Example.
        '''</summary>
        Friend Shared ReadOnly Property ExampleColumn() As String
            Get
                Return ResourceManager.GetString("ExampleColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FormName.
        '''</summary>
        Friend Shared ReadOnly Property FormNameColumn() As String
            Get
                Return ResourceManager.GetString("FormNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FromLocation.
        '''</summary>
        Friend Shared ReadOnly Property FromLocation() As String
            Get
                Return ResourceManager.GetString("FromLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HardwareID.
        '''</summary>
        Friend Shared ReadOnly Property HardwareIDColumn() As String
            Get
                Return ResourceManager.GetString("HardwareIDColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Date.
        '''</summary>
        Friend Shared ReadOnly Property InventoryDateColumn() As String
            Get
                Return ResourceManager.GetString("InventoryDateColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invoice Number.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceNumber() As String
            Get
                Return ResourceManager.GetString("InvoiceNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceStatus() As String
            Get
                Return ResourceManager.GetString("InvoiceStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalAmount.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceTotalAmount() As String
            Get
                Return ResourceManager.GetString("InvoiceTotalAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalDiscount.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceTotalDiscount() As String
            Get
                Return ResourceManager.GetString("InvoiceTotalDiscount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TypesEngName.
        '''</summary>
        Friend Shared ReadOnly Property InvoiceTypesEngName() As String
            Get
                Return ResourceManager.GetString("InvoiceTypesEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Code.
        '''</summary>
        Friend Shared ReadOnly Property ItemCodeColumn() As String
            Get
                Return ResourceManager.GetString("ItemCodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cost Price.
        '''</summary>
        Friend Shared ReadOnly Property ItemCostPrice() As String
            Get
                Return ResourceManager.GetString("ItemCostPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Name.
        '''</summary>
        Friend Shared ReadOnly Property ItemNameEngColumn() As String
            Get
                Return ResourceManager.GetString("ItemNameEngColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LicKey.
        '''</summary>
        Friend Shared ReadOnly Property LicKeyColumn() As String
            Get
                Return ResourceManager.GetString("LicKeyColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Code.
        '''</summary>
        Friend Shared ReadOnly Property LocationCodeColumn() As String
            Get
                Return ResourceManager.GetString("LocationCodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Name.
        '''</summary>
        Friend Shared ReadOnly Property LocationEngNameColumn() As String
            Get
                Return ResourceManager.GetString("LocationEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location ArName.
        '''</summary>
        Friend Shared ReadOnly Property LocationNameColumn() As String
            Get
                Return ResourceManager.GetString("LocationNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Type Code.
        '''</summary>
        Friend Shared ReadOnly Property LocationTypeCodeColumn() As String
            Get
                Return ResourceManager.GetString("LocationTypeCodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Type.
        '''</summary>
        Friend Shared ReadOnly Property LocationTypeEngNameColumn() As String
            Get
                Return ResourceManager.GetString("LocationTypeEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location ArType.
        '''</summary>
        Friend Shared ReadOnly Property LocationTypeNameColumn() As String
            Get
                Return ResourceManager.GetString("LocationTypeNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Cost Price.
        '''</summary>
        Friend Shared ReadOnly Property NewCostPrice() As String
            Get
                Return ResourceManager.GetString("NewCostPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Price.
        '''</summary>
        Friend Shared ReadOnly Property NewPrice() As String
            Get
                Return ResourceManager.GetString("NewPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Selling Price.
        '''</summary>
        Friend Shared ReadOnly Property NewSellingPrice() As String
            Get
                Return ResourceManager.GetString("NewSellingPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Cost Price.
        '''</summary>
        Friend Shared ReadOnly Property OldCostPrice() As String
            Get
                Return ResourceManager.GetString("OldCostPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Price.
        '''</summary>
        Friend Shared ReadOnly Property OldPrice() As String
            Get
                Return ResourceManager.GetString("OldPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Selling Price.
        '''</summary>
        Friend Shared ReadOnly Property OldSellingPrice() As String
            Get
                Return ResourceManager.GetString("OldSellingPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to On Order QTY.
        '''</summary>
        Friend Shared ReadOnly Property OnOrderQTYColumn() As String
            Get
                Return ResourceManager.GetString("OnOrderQTYColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OpenAmount.
        '''</summary>
        Friend Shared ReadOnly Property OpenAmountColumn() As String
            Get
                Return ResourceManager.GetString("OpenAmountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ar Package.
        '''</summary>
        Friend Shared ReadOnly Property PackageNameArColumn() As String
            Get
                Return ResourceManager.GetString("PackageNameArColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package.
        '''</summary>
        Friend Shared ReadOnly Property PackageNameEngColumn() As String
            Get
                Return ResourceManager.GetString("PackageNameEngColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Package Size.
        '''</summary>
        Friend Shared ReadOnly Property PackSizeColumn() As String
            Get
                Return ResourceManager.GetString("PackSizeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ar Payment Type.
        '''</summary>
        Friend Shared ReadOnly Property PaymentArName() As String
            Get
                Return ResourceManager.GetString("PaymentArName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment Type.
        '''</summary>
        Friend Shared ReadOnly Property PaymentEngName() As String
            Get
                Return ResourceManager.GetString("PaymentEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaAmountColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaAmountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NameArabic.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaArNameColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaArNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaEnNameColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaEnNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Photo.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaPhotoColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaPhotoColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pieces Count.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaPiecesCountColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaPiecesCountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property PaymentMediaTypeColumn() As String
            Get
                Return ResourceManager.GetString("PaymentMediaTypeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permission Category.
        '''</summary>
        Friend Shared ReadOnly Property PermissionCategory() As String
            Get
                Return ResourceManager.GetString("PermissionCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone1.
        '''</summary>
        Friend Shared ReadOnly Property Phone1Column() As String
            Get
                Return ResourceManager.GetString("Phone1Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone2.
        '''</summary>
        Friend Shared ReadOnly Property Phone2Column() As String
            Get
                Return ResourceManager.GetString("Phone2Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Physical QTY.
        '''</summary>
        Friend Shared ReadOnly Property PhysicalQTYColumn() As String
            Get
                Return ResourceManager.GetString("PhysicalQTYColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ar POS Machine.
        '''</summary>
        Friend Shared ReadOnly Property POSArName() As String
            Get
                Return ResourceManager.GetString("POSArName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to POS Machine.
        '''</summary>
        Friend Shared ReadOnly Property POSEngName() As String
            Get
                Return ResourceManager.GetString("POSEngName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printed QTY.
        '''</summary>
        Friend Shared ReadOnly Property PrintedQTYColumn() As String
            Get
                Return ResourceManager.GetString("PrintedQTYColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QTY.
        '''</summary>
        Friend Shared ReadOnly Property QTY() As String
            Get
                Return ResourceManager.GetString("QTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptNumber() As String
            Get
                Return ResourceManager.GetString("ReceiptNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReceiptType.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptTypeColumn() As String
            Get
                Return ResourceManager.GetString("ReceiptTypeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reorder Point.
        '''</summary>
        Friend Shared ReadOnly Property ReorderPointColumn() As String
            Get
                Return ResourceManager.GetString("ReorderPointColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reorder Qty.
        '''</summary>
        Friend Shared ReadOnly Property ReorderQtyColumn() As String
            Get
                Return ResourceManager.GetString("ReorderQtyColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReportName.
        '''</summary>
        Friend Shared ReadOnly Property ReportNameColumn() As String
            Get
                Return ResourceManager.GetString("ReportNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReportType.
        '''</summary>
        Friend Shared ReadOnly Property ReportTypeColumn() As String
            Get
                Return ResourceManager.GetString("ReportTypeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan DateTime.
        '''</summary>
        Friend Shared ReadOnly Property ScanDateTimeColumn() As String
            Get
                Return ResourceManager.GetString("ScanDateTimeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selection.
        '''</summary>
        Friend Shared ReadOnly Property Selection() As String
            Get
                Return ResourceManager.GetString("Selection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property SellingPriceColumn() As String
            Get
                Return ResourceManager.GetString("SellingPriceColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Barcode.
        '''</summary>
        Friend Shared ReadOnly Property SKUColumn() As String
            Get
                Return ResourceManager.GetString("SKUColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SN.
        '''</summary>
        Friend Shared ReadOnly Property SNColumn() As String
            Get
                Return ResourceManager.GetString("SNColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StartDateTime.
        '''</summary>
        Friend Shared ReadOnly Property StartDateTimeColumn() As String
            Get
                Return ResourceManager.GetString("StartDateTimeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier En Name.
        '''</summary>
        Friend Shared ReadOnly Property SupplierEngNameColumn() As String
            Get
                Return ResourceManager.GetString("SupplierEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Item Code.
        '''</summary>
        Friend Shared ReadOnly Property SupplierItemCodeColumn() As String
            Get
                Return ResourceManager.GetString("SupplierItemCodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Ar Name.
        '''</summary>
        Friend Shared ReadOnly Property SupplierNameColumn() As String
            Get
                Return ResourceManager.GetString("SupplierNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Ref.
        '''</summary>
        Friend Shared ReadOnly Property SupplierRefColumn() As String
            Get
                Return ResourceManager.GetString("SupplierRefColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ToLocation.
        '''</summary>
        Friend Shared ReadOnly Property ToLocation() As String
            Get
                Return ResourceManager.GetString("ToLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property Total() As String
            Get
                Return ResourceManager.GetString("Total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalDiscount.
        '''</summary>
        Friend Shared ReadOnly Property TotalDiscountColumn() As String
            Get
                Return ResourceManager.GetString("TotalDiscountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalExchange.
        '''</summary>
        Friend Shared ReadOnly Property TotalExchangeColumn() As String
            Get
                Return ResourceManager.GetString("TotalExchangeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalReturnAmount.
        '''</summary>
        Friend Shared ReadOnly Property TotalReturnAmountColumn() As String
            Get
                Return ResourceManager.GetString("TotalReturnAmountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TotalSalesAmount.
        '''</summary>
        Friend Shared ReadOnly Property TotalSalesAmountColumn() As String
            Get
                Return ResourceManager.GetString("TotalSalesAmountColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UrduCaption.
        '''</summary>
        Friend Shared ReadOnly Property UrduCaptionColumn() As String
            Get
                Return ResourceManager.GetString("UrduCaptionColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserName.
        '''</summary>
        Friend Shared ReadOnly Property UserEngNameColumn() As String
            Get
                Return ResourceManager.GetString("UserEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend Shared ReadOnly Property Value() As String
            Get
                Return ResourceManager.GetString("Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Code.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseCodeColumn() As String
            Get
                Return ResourceManager.GetString("WarehouseCodeColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Name.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseEngNameColumn() As String
            Get
                Return ResourceManager.GetString("WarehouseEngNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse ArName.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseNameColumn() As String
            Get
                Return ResourceManager.GetString("WarehouseNameColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warranty Date.
        '''</summary>
        Friend Shared ReadOnly Property WarrantyExpireDateColumn() As String
            Get
                Return ResourceManager.GetString("WarrantyExpireDateColumn", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
