Public Class FormController
    Public Shared objAddress As frmAddress
    'Public Shared objfrmAnonymAssets As frmAnonymAssets
    Public Shared objfrmApproved As frmPOApproved
    Public Shared objfrmAssetCodingDef As frmAssetCodingDef
    Public Shared objfrmItems As frmItems
    Public Shared objfrmAssetsDetails As frmAssetsDetails
    Public Shared objfrmAssetTransfer As frmAssetTransfer
    Public Shared objfrmAstInvSch As frmAstInvSch
    Public Shared objfrmAstSearch As frmAstSearch
    Public Shared objfrmAstWarrantyAlarm As frmAssetWarrantyAlarm
    Public Shared objfrmBarcodePolicy As frmBarcodePolicy
    Public Shared objfrmBarStuct As frmBarStuct
    Public Shared objfrmBlkQty As frmBlkQty
    Public Shared objfrmBookTempl As frmAstBooks
    Public Shared objfrmBrand As frmBrand
    Public Shared objfrmCat As frmCategory
    Public Shared objfrmCompanies As frmCompanies
    Public Shared objfrmCompany As frmCompany
    Public Shared objfrmCompanyTrans As frmCompanyTrans
    'Public Shared objfrmCostCenter As frmCostCenter
    Public Shared objfrmCustodian As frmCustodian
    Public Shared objfrmDashboard As frmDashboard
    Public Shared objfrmDesig As frmDesignation
    Public Shared objfrmGLCode As frmGLCodes
    Public Shared objfrmDep As frmDep
    Public Shared objfrmDevices As frmDevices
    Public Shared objfrmOfflineMachines As frmOfflineMachines
    Public Shared objfrmDepMan As frmDepMan
    Public Shared objfrmDepPolicy As frmDepPolicy
    Public Shared objfrmDisp As frmDisp
    Public Shared objfrmError As frmError
    Public Shared objfrmInsurar As frmInsurar
    Public Shared objfrmLocation As frmLocation
    Public Shared objfrmLogin As frmLogin
    Public Shared objfrmPOApproval As frmPOApproval
    Public Shared objfrmPODisplay As frmPODisplay
    Public Shared objfrmPOMaster As frmPOMaster
    Public Shared objfrmPOTrans As frmPOTrans
    Public Shared objfrmRoles As frmRoles
    Public Shared objfrmRptFilter As Form
    Public Shared objfrmSupplier As frmSupplier
    Public Shared objfrmSysConfig As frmSysConfig
    Public Shared objfrmUnits As frmUnits
    Public Shared objfrmUser As frmUser
    Public Shared objfrmReceive As frmReceive
    Public Shared objFrmLevels As frmLevels
    Public Shared objfrmOrgGroups As frmOrgGroups
    Public Shared objfrmOrgHier As frmOrgHier

    Public Shared objfrmSend As Form
    Public Shared objfrmDataProcessing As Form
    'Public Shared objfrmAuditReportFilter As frmRptAudit
    'Public Shared objrptCategoryReports As frmRptCategory
    Public Shared objfrmRptDesigner As frmReportDesigner
    Public Shared objfrmCostCenter As frmCostCenter
    Public Shared objfrmBackendInventory As frmBackendInventory

End Class