'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ZulResource.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Address() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Address", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Anonymous_Assets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anonymous_Assets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Application_Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Application_Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Administration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Administration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Categories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Categories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Details___Maintenance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Details___Maintenance", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Ledger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Ledger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Asset_Transfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Asset_Transfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets_Administration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets_Administration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets_Coding_Definition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets_Coding_Definition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets_Details() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets_Details", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets_in_Transit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets_in_Transit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Assets_Tagging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assets_Tagging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Audit_Status_Report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Audit_Status_Report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bar_Code_Structure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bar_Code_Structure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode_Designing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode_Designing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barcoding_policy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barcoding_policy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Black_Solid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Black_Solid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Book_Templates() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Book_Templates", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Companies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Companies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Company_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Company_Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property company_levels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company_levels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cost_Centers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cost_Centers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Custodians() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Custodians", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Data_Acquisition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Data_Acquisition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Data_Transmission() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Data_Transmission", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property departments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("departments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Depreciation_Books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Depreciation_Books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Depreciation_Engine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Depreciation_Engine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Depreciation_Methods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Depreciation_Methods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Depreciation_Policy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Depreciation_Policy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Designations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Designations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DesktopScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DesktopScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Devices_Configuration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Devices_Configuration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Disposal_Methods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disposal_Methods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Expected_Depreciation_Books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expected_Depreciation_Books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Forms_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forms_BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GL_codes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GL_codes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Insurers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Insurers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inter_Company_Transfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inter_Company_Transfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inventory_Schedules() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inventory_Schedules", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property items_inventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("items_inventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loading2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Location_Custody_Transfer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Location_Custody_Transfer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Locations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Manager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Manager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property New_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("New_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Organization_Groups() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Organization_Groups", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Organizational_Hierarchy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Organizational_Hierarchy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property P_O_Approvals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P_O_Approvals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Purchase_Orders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Purchase_Orders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Suppliers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suppliers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property System_Configurations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("System_Configurations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Transfer_PO_Items() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transfer_PO_Items", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Units() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Units", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Roles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User_Roles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZulAssets() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ZulAssets", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ZulAssets_Activation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZulAssets_Activation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZulAssets_Registration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZulAssets_Registration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZulItems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZulItems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
